<?php
/**
 * Plugin Name:       Accessible Video Block
 * Plugin URI:        https://courtneyr.dev
 * Description:       Gutenberg block that emits the [ableplayer] shortcode from a structured editor UI, with a JS-free inline transcript wrapper. Requires Joe Dolson's Able Player plugin.
 * Version:           0.1.0
 * Requires at least: 6.5
 * Requires PHP:      7.4
 * Requires Plugins:  ableplayer
 * Author:            Courtney Robertson
 * Author URI:        https://courtneyr.dev
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       accessible-video-block
 * Domain Path:       /languages
 */

declare( strict_types=1 );

namespace CourtneyR\AccessibleVideoBlock;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'COURTNEYR_AVB_VERSION', '0.1.0' );
define( 'COURTNEYR_AVB_FILE', __FILE__ );
define( 'COURTNEYR_AVB_DIR', plugin_dir_path( __FILE__ ) );
define( 'COURTNEYR_AVB_URL', plugin_dir_url( __FILE__ ) );

/**
 * Tiny PSR-4 autoloader for runtime. Avoids shipping composer's vendor/ on deploy.
 * Composer is still used for the dev environment (PHPUnit) but the autoloader
 * generated by composer is not relied on at runtime.
 */
spl_autoload_register( static function ( string $class ): void {
	$prefix = __NAMESPACE__ . '\\';
	if ( strpos( $class, $prefix ) !== 0 ) {
		return;
	}
	$relative = substr( $class, strlen( $prefix ) );
	$file     = COURTNEYR_AVB_DIR . 'includes/' . str_replace( '\\', '/', $relative ) . '.php';
	if ( is_readable( $file ) ) {
		require_once $file;
	}
} );

add_action( 'plugins_loaded', static function (): void {
	( new Plugin() )->register();
}, 20 );
